services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 pizza_crud.wsgi:application
    volumes:
      - .:/app
      - ./media:/media
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dev


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - dev


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - dev


volumes:
  sqlite_data:

networks:
  dev: