# Generated by Django 5.1.7 on 2025-08-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_ingredient_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='rest.restaurant'),
        ),
    ]
